CREATE TABLE User
(
    User_Id INT NOT NULL AUTO_INCREMENT,
    Email VARCHAR(256) NOT NULL UNIQUE,
    Password_Hash VARCHAR(256) NOT NULL,
    Display_Name VARCHAR(50) NOT NULL UNIQUE,
    First_Name VARCHAR(100) NOT NULL,
    Last_Name VARCHAR(100) NOT NULL,
    Active BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY(User_Id)
);
